#!/bin/bash
for count in {1..10}
do
date +%H:%M:%S
sleep .2
done
 
cat /proc/cpuinfo > /tmp/cpu.txt
cd /etc; ls | grep release | xargs cat | head -2 | tail -1 > /tmp/os.txt
 
cd /etc; ls | grep release | xargs cat | head -2 | tail -1 | sed s/NAME=\"// | sed s/\"// >> /tmp/os.txt
 
for file in {50..100}
do
touch "/tmp/$file.txt"
done
